# Site settings
title: Eu Sou Alec
tagline: Associação Livres em Cristo
description: A Alec oferece mais de 20 atividades, cursos e refeições diárias para crianças e adolescentes do Parque da Liberdade, em Americana/SP.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eusoualec.org.br" # the base hostname & protocol for your site
lang: pt-BR
logo: /assets/images/logo_alec.png
telefone: (19) 99129-2661
email: eusoualec@gmail.com
inscritos: 325
refeicoes: 300
voluntarios: 60

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - .rubocop.yml

defaults:
  # Imagem padrão usada em og:image / twitter:image ao compartilhar qualquer página
  - scope:
      path: ""
    values:
      image: /assets/images/slider/home-slider-1.jpg
  - scope:
      path: "assets/images/gallery"
    values:
      gallery: true
