# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eu Sou Alec
email: contato@eusoualec.org.br
description: > # this means to ignore newlines until "baseurl:"
  Eu Sou Alec - Associação Livres em Cristo
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eusoualec.org.br" # the base hostname & protocol for your site
telefone: (19) 3465-3218
email: associacaolivresemcristo@outlook.com

# Build settings
markdown: kramdown
exclude: [vendor]
